import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // ─── Admin user ────────────────────────────────────────
  const adminPassword = await bcrypt.hash('admin123', 12);
  const admin = await prisma.user.upsert({
    where: { phone: '0770000001' },
    update: {},
    create: {
      phone: '0770000001',
      email: 'admin@careeraccess.co.zw',
      passwordHash: adminPassword,
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      isVerified: true,
    },
  });
  console.log('Admin user created:', admin.id);

  // ─── Institutions ──────────────────────────────────────
  const institutions = await Promise.all([
    prisma.institution.create({
      data: {
        name: 'University of Zimbabwe',
        type: 'UNIVERSITY',
        province: 'Harare',
        city: 'Harare',
        address: 'P.O. Box MP167, Mount Pleasant, Harare',
        phone: '+263 4 303211',
        email: 'info@uz.ac.zw',
        website: 'https://www.uz.ac.zw',
        description: 'The oldest and most prestigious university in Zimbabwe, established in 1952.',
        isMember: true,
        isVerified: true,
        portalUrl: 'https://apply.uz.ac.zw',
      },
    }),
    prisma.institution.create({
      data: {
        name: 'National University of Science and Technology',
        type: 'UNIVERSITY',
        province: 'Bulawayo',
        city: 'Bulawayo',
        address: 'P.O. Box AC939, Ascot, Bulawayo',
        phone: '+263 29 282842',
        email: 'info@nust.ac.zw',
        website: 'https://www.nust.ac.zw',
        description: 'Zimbabwe\'s leading science and technology university.',
        isMember: true,
        isVerified: true,
        portalUrl: 'https://apply.nust.ac.zw',
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Midlands State University',
        type: 'UNIVERSITY',
        province: 'Midlands',
        city: 'Gweru',
        address: 'P Bag 9055, Gweru',
        phone: '+263 54 260404',
        email: 'info@msu.ac.zw',
        website: 'https://www.msu.ac.zw',
        description: 'A vibrant state university offering diverse programmes.',
        isMember: true,
        isVerified: true,
        portalUrl: 'https://apply.msu.ac.zw',
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Chinhoyi University of Technology',
        type: 'UNIVERSITY',
        province: 'Mashonaland West',
        city: 'Chinhoyi',
        address: 'P. Bag 7724, Chinhoyi',
        phone: '+263 67 22203',
        email: 'info@cut.ac.zw',
        website: 'https://www.cut.ac.zw',
        description: 'Technology-focused university with strong practical training.',
        isMember: true,
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Harare Polytechnic',
        type: 'POLYTECHNIC',
        province: 'Harare',
        city: 'Harare',
        address: 'P.O. Box CY 407, Causeway, Harare',
        phone: '+263 4 752311',
        description: 'Zimbabwe\'s premier polytechnic for technical and vocational training.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Bulawayo Polytechnic',
        type: 'POLYTECHNIC',
        province: 'Bulawayo',
        city: 'Bulawayo',
        address: 'P.O. Box 1392, Bulawayo',
        phone: '+263 29 68281',
        description: 'Leading polytechnic in the Matabeleland region.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Kwekwe Polytechnic',
        type: 'POLYTECHNIC',
        province: 'Midlands',
        city: 'Kwekwe',
        description: 'Polytechnic offering technical and business programmes.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Speciss College',
        type: 'PRIVATE_COLLEGE',
        province: 'Harare',
        city: 'Harare',
        address: 'Jason Moyo Avenue, Harare',
        phone: '+263 4 700596',
        website: 'https://www.speciss.co.zw',
        description: 'Leading private college for business and IT programmes.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Zimbabwe School of Mines',
        type: 'VOCATIONAL',
        province: 'Midlands',
        city: 'Kwekwe',
        description: 'Specialized institution for mining and metallurgy training.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Belvedere Teachers College',
        type: 'TEACHERS_COLLEGE',
        province: 'Harare',
        city: 'Harare',
        description: 'One of Zimbabwe\'s leading teacher training colleges.',
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Great Zimbabwe University',
        type: 'UNIVERSITY',
        province: 'Masvingo',
        city: 'Masvingo',
        address: 'P.O. Box 1235, Masvingo',
        phone: '+263 39 252227',
        website: 'https://www.gzu.ac.zw',
        description: 'University with strong arts, education and agriculture programmes.',
        isMember: true,
        isVerified: true,
      },
    }),
    prisma.institution.create({
      data: {
        name: 'Lupane State University',
        type: 'UNIVERSITY',
        province: 'Matabeleland North',
        city: 'Lupane',
        website: 'https://www.lsu.ac.zw',
        description: 'State university serving the Matabeleland North region.',
        isVerified: true,
      },
    }),
  ]);

  const [uz, nust, msu, cut, harePoly, bulPoly, kwePoly, speciss, zsm, belvedere, gzu, lsu] = institutions;
  console.log(`Created ${institutions.length} institutions`);

  // ─── Programmes ────────────────────────────────────────
  const programmes = await Promise.all([
    // University of Zimbabwe
    prisma.programme.create({
      data: {
        institutionId: uz.id,
        name: 'Bachelor of Science Honours in Computer Science',
        code: 'BSCS',
        qualificationLevel: 'HONOURS',
        faculty: 'Science',
        department: 'Computer Science',
        description: 'Comprehensive programme covering software engineering, algorithms, AI, and systems design.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1500,
        tuitionFeeMax: 2500,
        entryRequirements: { minimumLevel: 'A_LEVEL', minimumPoints: 10 },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Mathematics', 'English'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Birth Certificate', 'Passport Photo'],
        applicationFee: 30,
        demandScore: 85,
        remoteOpportunity: 90,
        selfEmployment: 80,
        capitalRequirement: 20,
        timeToIncome: 60,
        aiAutomationRisk: 30,
        overallValueScore: 82,
        sourceUrl: 'https://www.uz.ac.zw/science/computer-science',
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: uz.id,
        name: 'Bachelor of Laws (LLB)',
        code: 'LLB',
        qualificationLevel: 'HONOURS',
        faculty: 'Law',
        description: 'Professional law degree covering constitutional, criminal, commercial and international law.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 2000,
        tuitionFeeMax: 3000,
        entryRequirements: { minimumLevel: 'A_LEVEL', minimumPoints: 12 },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['English'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 30,
        demandScore: 70,
        remoteOpportunity: 40,
        selfEmployment: 75,
        capitalRequirement: 40,
        timeToIncome: 40,
        aiAutomationRisk: 45,
        overallValueScore: 65,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: uz.id,
        name: 'Bachelor of Medicine and Surgery (MBChB)',
        code: 'MBCHB',
        qualificationLevel: 'BACHELOR',
        faculty: 'Health Sciences',
        description: 'Medical degree programme training doctors for Zimbabwe and beyond.',
        durationMonths: 66,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 3000,
        tuitionFeeMax: 5000,
        entryRequirements: { minimumLevel: 'A_LEVEL', minimumPoints: 14, requiredALevel: ['Chemistry', 'Biology'] },
        oLevelMin: 5,
        aLevelMin: 3,
        requiredSubjects: ['Mathematics', 'English', 'Chemistry', 'Biology'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Birth Certificate', 'Passport Photo'],
        applicationFee: 50,
        demandScore: 95,
        remoteOpportunity: 50,
        selfEmployment: 70,
        capitalRequirement: 60,
        timeToIncome: 30,
        aiAutomationRisk: 15,
        overallValueScore: 88,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: uz.id,
        name: 'Bachelor of Accounting Honours',
        code: 'BACC',
        qualificationLevel: 'HONOURS',
        faculty: 'Commerce',
        department: 'Accounting',
        description: 'Professional accounting degree with pathway to CA(Z) qualification.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1500,
        tuitionFeeMax: 2500,
        entryRequirements: { minimumLevel: 'A_LEVEL', minimumPoints: 10 },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Mathematics', 'English', 'Accounting'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 30,
        demandScore: 80,
        remoteOpportunity: 60,
        selfEmployment: 70,
        capitalRequirement: 20,
        timeToIncome: 55,
        aiAutomationRisk: 55,
        overallValueScore: 70,
        lastVerifiedAt: new Date(),
      },
    }),

    // NUST
    prisma.programme.create({
      data: {
        institutionId: nust.id,
        name: 'Bachelor of Engineering Honours in Electronic Engineering',
        qualificationLevel: 'HONOURS',
        faculty: 'Engineering',
        department: 'Electronic Engineering',
        description: 'Engineering degree covering electronics, telecommunications, and embedded systems.',
        durationMonths: 60,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1800,
        tuitionFeeMax: 2800,
        entryRequirements: { minimumLevel: 'A_LEVEL', minimumPoints: 10 },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Mathematics', 'Physics'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 75,
        remoteOpportunity: 50,
        selfEmployment: 60,
        capitalRequirement: 40,
        timeToIncome: 50,
        aiAutomationRisk: 25,
        overallValueScore: 72,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: nust.id,
        name: 'Bachelor of Science Honours in Applied Physics',
        qualificationLevel: 'HONOURS',
        faculty: 'Science',
        description: 'Applied physics programme with strong practical and research components.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1500,
        tuitionFeeMax: 2200,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Mathematics', 'Physics'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 55,
        remoteOpportunity: 40,
        selfEmployment: 30,
        capitalRequirement: 50,
        timeToIncome: 45,
        aiAutomationRisk: 20,
        overallValueScore: 55,
        lastVerifiedAt: new Date(),
      },
    }),

    // Midlands State University
    prisma.programme.create({
      data: {
        institutionId: msu.id,
        name: 'Bachelor of Commerce in Marketing',
        qualificationLevel: 'BACHELOR',
        faculty: 'Commerce',
        department: 'Marketing',
        description: 'Marketing degree with focus on digital marketing and consumer behaviour.',
        durationMonths: 48,
        studyModes: ['FULL_TIME', 'PART_TIME'],
        tuitionFeeMin: 1200,
        tuitionFeeMax: 1800,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['English'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 65,
        remoteOpportunity: 70,
        selfEmployment: 75,
        capitalRequirement: 15,
        timeToIncome: 60,
        aiAutomationRisk: 50,
        overallValueScore: 68,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: msu.id,
        name: 'Bachelor of Science Honours in Information Systems',
        qualificationLevel: 'HONOURS',
        faculty: 'Science and Technology',
        description: 'Information systems degree bridging business and technology.',
        durationMonths: 48,
        studyModes: ['FULL_TIME', 'BLOCK_RELEASE'],
        tuitionFeeMin: 1300,
        tuitionFeeMax: 2000,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Mathematics'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 80,
        remoteOpportunity: 85,
        selfEmployment: 75,
        capitalRequirement: 15,
        timeToIncome: 65,
        aiAutomationRisk: 35,
        overallValueScore: 78,
        lastVerifiedAt: new Date(),
      },
    }),

    // Harare Polytechnic
    prisma.programme.create({
      data: {
        institutionId: harePoly.id,
        name: 'National Diploma in Information Technology',
        qualificationLevel: 'NATIONAL_DIPLOMA',
        faculty: 'Information Technology',
        description: 'Practical IT diploma covering networking, programming, and database management.',
        durationMonths: 36,
        studyModes: ['FULL_TIME', 'BLOCK_RELEASE'],
        tuitionFeeMin: 800,
        tuitionFeeMax: 1200,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['Mathematics', 'English'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 15,
        demandScore: 80,
        remoteOpportunity: 75,
        selfEmployment: 70,
        capitalRequirement: 15,
        timeToIncome: 75,
        aiAutomationRisk: 35,
        overallValueScore: 75,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: harePoly.id,
        name: 'National Diploma in Electrical Engineering',
        qualificationLevel: 'NATIONAL_DIPLOMA',
        faculty: 'Engineering',
        description: 'Electrical engineering diploma covering power systems, electronics, and installations.',
        durationMonths: 36,
        studyModes: ['FULL_TIME', 'BLOCK_RELEASE'],
        tuitionFeeMin: 900,
        tuitionFeeMax: 1400,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['Mathematics', 'Physical Science'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 15,
        demandScore: 75,
        remoteOpportunity: 30,
        selfEmployment: 80,
        capitalRequirement: 30,
        timeToIncome: 70,
        aiAutomationRisk: 15,
        overallValueScore: 72,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: harePoly.id,
        name: 'National Certificate in Automotive Engineering',
        qualificationLevel: 'NATIONAL_CERTIFICATE',
        faculty: 'Engineering',
        description: 'Hands-on automotive engineering certificate for motor vehicle mechanics.',
        durationMonths: 24,
        studyModes: ['FULL_TIME', 'BLOCK_RELEASE'],
        tuitionFeeMin: 500,
        tuitionFeeMax: 800,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 3,
        requiredSubjects: ['English'],
        requiredDocuments: ['O-Level Certificate', 'National ID'],
        applicationFee: 10,
        demandScore: 70,
        remoteOpportunity: 10,
        selfEmployment: 90,
        capitalRequirement: 35,
        timeToIncome: 80,
        aiAutomationRisk: 10,
        overallValueScore: 70,
        lastVerifiedAt: new Date(),
      },
    }),

    // Speciss College
    prisma.programme.create({
      data: {
        institutionId: speciss.id,
        name: 'Diploma in Business Management',
        qualificationLevel: 'DIPLOMA',
        faculty: 'Business',
        description: 'Comprehensive business management diploma with practical focus.',
        durationMonths: 24,
        studyModes: ['FULL_TIME', 'PART_TIME'],
        tuitionFeeMin: 1000,
        tuitionFeeMax: 1800,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['English', 'Mathematics'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 20,
        demandScore: 60,
        remoteOpportunity: 50,
        selfEmployment: 80,
        capitalRequirement: 30,
        timeToIncome: 65,
        aiAutomationRisk: 40,
        overallValueScore: 62,
        lastVerifiedAt: new Date(),
      },
    }),
    prisma.programme.create({
      data: {
        institutionId: speciss.id,
        name: 'Diploma in Software Engineering',
        qualificationLevel: 'DIPLOMA',
        faculty: 'Information Technology',
        description: 'Practical software development diploma covering web, mobile, and database technologies.',
        durationMonths: 24,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1200,
        tuitionFeeMax: 2000,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['Mathematics', 'English'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 20,
        demandScore: 85,
        remoteOpportunity: 90,
        selfEmployment: 85,
        capitalRequirement: 10,
        timeToIncome: 80,
        aiAutomationRisk: 30,
        overallValueScore: 85,
        lastVerifiedAt: new Date(),
      },
    }),

    // CUT
    prisma.programme.create({
      data: {
        institutionId: cut.id,
        name: 'Bachelor of Technology in Biotechnology',
        qualificationLevel: 'BACHELOR',
        faculty: 'Science and Technology',
        description: 'Biotechnology degree with laboratory and research components.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1400,
        tuitionFeeMax: 2200,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Biology', 'Chemistry'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 55,
        remoteOpportunity: 30,
        selfEmployment: 40,
        capitalRequirement: 60,
        timeToIncome: 45,
        aiAutomationRisk: 20,
        overallValueScore: 50,
        lastVerifiedAt: new Date(),
      },
    }),

    // Belvedere Teachers College
    prisma.programme.create({
      data: {
        institutionId: belvedere.id,
        name: 'Diploma in Education (Primary)',
        qualificationLevel: 'DIPLOMA',
        faculty: 'Education',
        description: 'Teacher training diploma for primary school education.',
        durationMonths: 36,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 600,
        tuitionFeeMax: 1000,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['English', 'Mathematics'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Birth Certificate', 'Passport Photo'],
        applicationFee: 15,
        demandScore: 65,
        remoteOpportunity: 20,
        selfEmployment: 40,
        capitalRequirement: 20,
        timeToIncome: 70,
        aiAutomationRisk: 25,
        overallValueScore: 60,
        lastVerifiedAt: new Date(),
      },
    }),

    // Zimbabwe School of Mines
    prisma.programme.create({
      data: {
        institutionId: zsm.id,
        name: 'National Certificate in Mining Engineering',
        qualificationLevel: 'NATIONAL_CERTIFICATE',
        faculty: 'Mining',
        description: 'Mining engineering certificate covering mine surveying, geology, and safety.',
        durationMonths: 24,
        studyModes: ['FULL_TIME', 'BLOCK_RELEASE'],
        tuitionFeeMin: 700,
        tuitionFeeMax: 1100,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['Mathematics', 'Physical Science'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 15,
        demandScore: 75,
        remoteOpportunity: 15,
        selfEmployment: 50,
        capitalRequirement: 70,
        timeToIncome: 75,
        aiAutomationRisk: 20,
        overallValueScore: 65,
        lastVerifiedAt: new Date(),
      },
    }),

    // GZU
    prisma.programme.create({
      data: {
        institutionId: gzu.id,
        name: 'Bachelor of Science in Agriculture',
        qualificationLevel: 'BACHELOR',
        faculty: 'Agriculture',
        description: 'Agriculture degree covering crop science, animal science, and agribusiness.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1200,
        tuitionFeeMax: 1800,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Biology'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 70,
        remoteOpportunity: 25,
        selfEmployment: 85,
        capitalRequirement: 50,
        timeToIncome: 55,
        aiAutomationRisk: 15,
        overallValueScore: 67,
        lastVerifiedAt: new Date(),
      },
    }),

    // Bulawayo Polytechnic
    prisma.programme.create({
      data: {
        institutionId: bulPoly.id,
        name: 'National Diploma in Hospitality Management',
        qualificationLevel: 'NATIONAL_DIPLOMA',
        faculty: 'Business',
        description: 'Hospitality management diploma covering hotel operations, food service, and tourism.',
        durationMonths: 36,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 700,
        tuitionFeeMax: 1100,
        entryRequirements: { minimumLevel: 'O_LEVEL' },
        oLevelMin: 5,
        requiredSubjects: ['English'],
        requiredDocuments: ['O-Level Certificate', 'National ID', 'Passport Photo'],
        applicationFee: 15,
        demandScore: 55,
        remoteOpportunity: 20,
        selfEmployment: 70,
        capitalRequirement: 45,
        timeToIncome: 70,
        aiAutomationRisk: 20,
        overallValueScore: 55,
        lastVerifiedAt: new Date(),
      },
    }),

    // Lupane State University
    prisma.programme.create({
      data: {
        institutionId: lsu.id,
        name: 'Bachelor of Science in Nursing',
        qualificationLevel: 'BACHELOR',
        faculty: 'Health Sciences',
        description: 'Professional nursing degree preparing registered nurses for Zimbabwe\'s healthcare system.',
        durationMonths: 48,
        studyModes: ['FULL_TIME'],
        tuitionFeeMin: 1200,
        tuitionFeeMax: 2000,
        entryRequirements: { minimumLevel: 'A_LEVEL' },
        oLevelMin: 5,
        aLevelMin: 2,
        requiredSubjects: ['Biology', 'Chemistry', 'English'],
        requiredDocuments: ['O-Level Certificate', 'A-Level Certificate', 'National ID', 'Birth Certificate', 'Passport Photo'],
        applicationFee: 25,
        demandScore: 90,
        remoteOpportunity: 40,
        selfEmployment: 30,
        capitalRequirement: 30,
        timeToIncome: 60,
        aiAutomationRisk: 10,
        overallValueScore: 80,
        lastVerifiedAt: new Date(),
      },
    }),
  ]);

  console.log(`Created ${programmes.length} programmes`);

  // ─── Intakes ───────────────────────────────────────────
  const intakeData = programmes.map((prog) => ({
    programmeId: prog.id,
    name: 'February',
    year: 2026,
    opensAt: new Date('2025-08-01'),
    closesAt: new Date('2025-12-31'),
    startsAt: new Date('2026-02-01'),
    isOpen: true,
  }));

  await prisma.intake.createMany({ data: intakeData });
  console.log(`Created ${intakeData.length} intakes`);

  // ─── Application Playbooks ────────────────────────────
  await prisma.applicationPlaybook.createMany({
    data: [
      {
        institutionName: 'University of Zimbabwe',
        portalUrl: 'https://apply.uz.ac.zw',
        steps: [
          { step: 1, instruction: 'Visit https://apply.uz.ac.zw and click "Create Account"' },
          { step: 2, instruction: 'Fill in your personal details (name, ID number, date of birth)' },
          { step: 3, instruction: 'Select your faculty and preferred programme' },
          { step: 4, instruction: 'Enter your O-Level and/or A-Level results (subject and grade)' },
          { step: 5, instruction: 'Upload scanned copies of your certificates (PDF or JPG)' },
          { step: 6, instruction: 'Pay the application fee via EcoCash or bank transfer' },
          { step: 7, instruction: 'Review your application and click Submit' },
          { step: 8, instruction: 'Save your application reference number' },
        ],
        paymentGuide: 'Application fee payable via EcoCash to merchant code 12345 or bank deposit to UZ account at CBZ Bank.',
        lastVerifiedAt: new Date(),
      },
      {
        institutionName: 'National University of Science and Technology',
        portalUrl: 'https://apply.nust.ac.zw',
        steps: [
          { step: 1, instruction: 'Go to https://apply.nust.ac.zw' },
          { step: 2, instruction: 'Register with your email and phone number' },
          { step: 3, instruction: 'Complete personal information section' },
          { step: 4, instruction: 'Choose your programme under the correct faculty' },
          { step: 5, instruction: 'Enter your academic qualifications' },
          { step: 6, instruction: 'Upload supporting documents' },
          { step: 7, instruction: 'Pay application fee online or via mobile money' },
          { step: 8, instruction: 'Submit and note your reference number' },
        ],
        paymentGuide: 'Pay via InnBucks, EcoCash, or direct bank transfer to NUST account at FBC Bank.',
        lastVerifiedAt: new Date(),
      },
    ],
  });
  console.log('Created application playbooks');

  // ─── Sample learner ────────────────────────────────────
  const learnerPassword = await bcrypt.hash('learner123', 12);
  const learner = await prisma.user.upsert({
    where: { phone: '0771234567' },
    update: {},
    create: {
      phone: '0771234567',
      email: 'student@example.com',
      passwordHash: learnerPassword,
      firstName: 'Tendai',
      lastName: 'Moyo',
      role: 'LEARNER',
      dateOfBirth: new Date('2005-06-15'),
    },
  });

  await prisma.learnerProfile.upsert({
    where: { userId: learner.id },
    update: {},
    create: {
      userId: learner.id,
      educationLevel: 'O_LEVEL',
      school: 'Churchill High School',
      province: 'Harare',
      city: 'Harare',
      budgetMin: 500,
      budgetMax: 2000,
      studyMode: 'FULL_TIME',
      interests: ['Technology', 'Business'],
      strengths: ['logical', 'numerical'],
      oLevelResults: {
        Mathematics: 'A',
        English: 'B',
        'Physical Science': 'B',
        Accounting: 'A',
        Geography: 'C',
        History: 'C',
        Shona: 'B',
        'Computer Science': 'A',
      },
    },
  });
  console.log('Created sample learner:', learner.id);

  console.log('\nSeeding complete!');
  console.log('\nTest accounts:');
  console.log('  Admin: phone=0770000001 password=admin123');
  console.log('  Learner: phone=0771234567 password=learner123');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
